[data]
float_type = "double"
ensemble_dir = "/home/gialu/data/MetaQCD/test_hmc"
randomseed = 0
overwrite = true
verboselevel = 1
log_to_console = true

[ensemble]
L = [4, 4, 4, 4]
numtherm = 10
numsteps = 10
initial = "cold"
update_method = "hmc"
metro_numhits = 10
metro_target_acc = 0.5
metro_epsilon = 0.1
or_algorithm = "subgroups"
numorelax = 4

[gauge_action]
beta = 6.0
gauge_action = "wilson"

[hmc]
hmc_trajectory = 1
[[hmc.levels]]
forces = [1] # force 1: gauge action
integrator = "OMF4"
numsteps = 5

[gradient_flow]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

kmeasurements.Plaquette]
measure_every = 10

[measurements.Topological_charge]
measure_every = 10
type = ["plaquette", "clover"]

[measurements.Energy_density]
measure_every = 1
type = ["plaquette", "clover", "improved"]

[measurements.Gauge_action]
measure_every = 1
type = ["wilson", "symanzik_tree", "iwasaki", "dbw2"]

[measurements.Polyakov_loop]
measure_every = 1

[measurements.Wilson_loop]
measure_every = 1
Rmax = 2
Tmax = 2

[measurements_with_flow.Plaquette]
measure_every = 10

[measurements_with_flow.Topological_charge]
measure_every = 10
type = ["plaquette", "clover"]

[measurements_with_flow.Wilson_loop]
measure_every = 10
Rmax = 2
Tmax = 2
