["Physical Settings"]
L = [8, 8, 8, 8]
beta = 5.70
kind_of_gaction = "wilson"
numtherm = 10
numsteps = 10
initial = "cold"
update_method = "heatbath"
hb_maxit = 10
numheatbath = 1
eo = true
numorelax = 4
parity_update = true

["System Settings"]               
logdir = "./logs/L8x8x8x8_wilson_beta5.7/test_heatbath"
logfile = "logs.txt"
measurement_basedir = "./measurements/L8x8x8x8_wilson_beta5.7/test_heatbath"
measurement_dir = "raw_data"
randomseed = 0 # 0 => randomly chosen seed
verboselevel = 1
overwrite = true

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 10
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["clover"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 9
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 9

    [gradientflow_measurements.measurements_with_flow]


