["Physical Settings"]
L = [8, 8, 8, 8]
beta = 6.0
kind_of_gaction = "wilson"
numtherm = 10
numsteps = 10
initial = "cold"
update_method = "HMC"

["Bias Settings"]
# bias parameters
kind_of_bias = "opes"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = false
symmetric = true
stride = 1
cvlims = [-6, 6]
biasfactor = "Inf"
# usebiases = ["./metapotentials/L8x8x8x8_wilson_beta6.0/test_build/stream_1.txt"]
# metadynamics specific parameters
bin_width = 0.01
meta_weight = 0.02
penalty_weight = 1000
# opes specific parameters
barrier = 40
sigma0 = 0.1

["HMC Settings"]
hmc_deltatau = 0.2
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]               
logdir = "./logs/L8x8x8x8_wilson_beta6.0"
logfile = "test_build.txt"
measurement_basedir = "./measurements/L8x8x8x8_wilson_beta6.0"
measurement_dir = "test_build"
randomseed = 1206
verboselevel = 1
bias_basedir = "./metapotentials/L8x8x8x8_wilson_beta6.0"
bias_dir = "test_build"
overwrite = true

["Measurement set".measurement_methods.Plaquette]
measure_every = 5
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 10
flow_steps = 10
flow_tf = 0.1
flow_measure_every = 2

    [gradientflow_measurements.measurements_with_flow]
