[ensemble]
L = [4, 4, 4, 4]
numtherm = 20
numsteps = 10
initial = "cold"
update_method = "hmc"
parity_update = false
backend = "cpu"
float_type = "double"
# numprocs_cart = [1, 1, 1, 1]
# halo_width = 1

[data]
# ensemble_dir = ""
randomseed = 0
overwrite = true
# save_checkpoint_every = 10
# save_config_format = "bridge"
# save_config_every = 10
verboselevel = 1
log_to_console = true
# load_checkpoint_fromfile = true
# load_checkpoint_path = ""

[gauge_action]
beta = 0.95
gauge_action = "dbw2"

# TODO: Try staggered preconditioning ala hep-lat/0610047 via this twisted mass formalism and RationalFunctionApproximation
[fermion_action]
fermion_action = "staggered"
wilson_csw = 1.0
# twisted_mass = [0.01, 1.0]
[fermion_action.fermions.1]
Nf = 2
mass = [0.05, 0.005] # numerator mass and denominator mass
# hasenbush = true
# num_pseudoferm = 3
cg_tol_action = [1e-19]
cg_tol_md = [1e-8]
cg_maxiters_action = [5000]
cg_maxiters_md = [1000]
rhmc_spectral_bound = [[0.000025, 6.0]]
[fermion_action.fermions.2]
Nf = 3
mass = 0.05 # only denominator mass
hasenbush = true
num_pseudoferm = 2
cg_tol_action = [1e-19]
cg_tol_md = [1e-10]
cg_maxiters_action = [5000]
cg_maxiters_md = [5000]
rhmc_spectral_bound = [[0.0025, 6.0]]

[hmc]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"
# hmc_numsmear_fermion = 4
# hmc_rhostout_fermion = 0.125
hmc_levels = 1

[hmc.levels.1] # Gauge action - finest
ids = [0, 1, 2] # 0: gauge actio
integrator = "OMF4"
hmc_steps = 5
# [hmc.levels.2] # PF action - largest masses
# ids = ["strange_1", "light_2"]
# integrator = "OMF4"
# hmc_steps = 5
# [hmc.levels.3] # PF action - smallest masses
# ids = ["light_1"]
# integrator = "OMF2"
# hmc_steps = 5

[gradient_flow]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

[measurements.Plaquette]
measure_every = 10

[measurements.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["plaquette", "clover"]

[measurements_with_flow.Plaquette]
measure_every = 10

[measurements_with_flow.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["plaquette", "clover"]
