["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
gauge_action = "dbw2"
numtherm = 10
numsteps = 10
initial = "cold"
update_method = "HMC"

["Bias Settings"]
kind_of_bias = "opes"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = false
symmetric = true
stride = 1
cvlims = [-5, 5]
biasfactor = "Inf"
# metadynamics specific parameters
bin_width = 0.01
meta_weight = 0.02
penalty_weight = 100
# opes specific parameters
barrier = 40
sigma0 = 0.1

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]               
ensemble_dir = "test_build"
randomseed = 0
verboselevel = 2
overwrite = true

["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["clover"]

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 30
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 30

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]
