["Physical Settings"]
L = [4, 4, 4, 4]
"Î²" = 5.7
kind_of_gaction = "wilson"
Ntherm = 1
Nsteps = 10
initial = "cold"
update_method = "heatbath"
hb_MAXIT = 10
hb_numHB = 1
eo = true
numOR = 4
parity_update = false

["System Settings"]               
logdir = "./logs/L4x4x4x4_beta5.7"
logfile = "test_heatbath.txt"
measurement_basedir = "./measurements/L4x4x4x4_beta5.7"
measurement_dir = "test_heatbath"
randomseed = 0 # 0 => randomly chosen seed
verboselevel = 1
overwrite = true

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 10
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["clover"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 1
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 1

    [gradientflow_measurements.measurements_with_flow.Topological_charge]
    measure_every = 10
    methodname = "topological_charge"
    kinds_of_topological_charge = ["clover"]

    [gradientflow_measurements.measurements_with_flow.Plaquette]
    measure_every = 10
    methodname = "plaquette"


