["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
gauge_action = "dbw2"
numtherm = 5
numsteps = 1
initial = "cold"
update_method = "HMC"

["Bias Settings"]
# general bias parameters
kind_of_bias = "parametric"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = false
symmetric = true
stride = 1
cvlims = [-5, 5]
biasfactor = "Inf"
penalty_weight = 100
# metadynamics specific parameters
bin_width = 0.02
meta_weight = 0.01
# opes specific parameters
barrier = 40
sigma0 = 0.1
# parametric values
bias_Q = 0.0
bias_A = 8
bias_Z = 1.18
# usebiases = [
#     "./metapotentials/L16x16x16x16_dbw2_beta1.25/dummy.txt",
# ]

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]
float_type = "double"            
# ensemble_dir = ""
randomseed = 0
verboselevel = 2
overwrite = true

["Measurement Settings".measurements.Energy_density]
measure_every = 1
kinds_of_energy_density = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Gauge_action]
measure_every = 1
kinds_of_gauge_action = ["wilson", "symanzik_tree", "iwasaki", "dbw2"]

["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Polyakov_loop]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Wilson_loop]
measure_every = 1
Rmax = 2
Tmax = 2

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]

    ["Gradient Flow Settings".measurements_with_flow.Wilson_loop]
    measure_every = 10
    Rmax = 2
    Tmax = 2
