["Physical Settings"]
L = [4, 4, 4, 4]
beta = 6.0
gauge_action = "wilson"
numtherm = 1
numsteps = 1
initial = "cold"
update_method = "hmc"
parity_update = false
numprocs_cart = [1, 1, 1, 1]
halo_width = 1

["Dynamical Fermion Settings"]
fermion_action = "staggered"
eo_precon = false
Nf = [8]
mass = [0.0]
wilson_csw = 1.0
cg_tol_action = 1e-16
cg_tol_md = 1e-16
cg_maxiters_action = 5000
cg_maxiters_md = 5000
rhmc_spectral_bound = [0.0001, 6.0]
rhmc_prec_action = 64
rhmc_prec_md = 64

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"
hmc_numsmear_fermion = 0
hmc_rhostout_fermion = 0.12

["System Settings"]
backend = "cuda"
float_type = "double"
# ensemble_dir = ""
randomseed = 0
overwrite = true
# save_checkpoint_every = 10
# save_config_format = "bridge"
# save_config_every = 10
verboselevel = 1
log_to_console = true
# load_checkpoint_fromfile = true
# load_checkpoint_path = ""

["Measurement Settings".measurements]
["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
type = ["plaquette", "clover"]
    
["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

    ["Gradient Flow Settings".measurements_with_flow]
    ["Gradient Flow Settings".measurements_with_flow.Plaquette]
    measure_every = 1

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 1
    type = ["plaquette", "clover"]
