["Physical Settings"]
L = [8, 8, 8, 8]
"β" = 5.70
kind_of_gaction = "symanzik_tadpole"
Ntherm = 10
Nsteps = 100
initial = "cold"
update_method = "hmc"
parity_update = true

["HMC related"]
"hmc_Δτ" = 0.1
hmc_steps = 10
hmc_integrator = "OMF4"

["System Settings"]               
logdir = "./logs/L8x8x8x8_beta5.7"
logfile = "test_wilson.txt"
measurement_basedir = "./measurements/L8x8x8x8_beta5.7"
measurement_dir = "test_wilson"
randomseed = 0 # 0 => randomly chosen seed
verboselevel = 2
overwrite = true

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 10
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["clover"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 9
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 9

    [gradientflow_measurements.measurements_with_flow]


