["Physical Settings"]
L = [4, 4, 4, 4]
beta = 3.5
kind_of_gaction = "symanzik_tree"
numtherm = 20
numsteps = 10
initial = "cold"
update_method = "hmc"
parity_update = false

["Dynamical Fermion Settings"]
fermion_action = "staggered"
eo_precon = true
Nf = [4]
mass = [0.1]
cg_tol_action = 1e-16
cg_tol_md = 1e-16
cg_maxiters_action = 5000
cg_maxiters_md = 5000

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"
hmc_numsmear_fermion = 4
hmc_rhostout_fermion = 0.12

["System Settings"]
backend = "cpu"
float_type = "double"
ensemble_dir = "fermion_test"
randomseed = 0
verboselevel = 1
overwrite = true

["Measurement Settings".measurements.Plaquette]
measure_every = 5

["Measurement Settings".measurements.Pion_correlator]
measure_every = 5
dirac_type = "wilson"

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

["Gradient Flow Settings".measurements_with_flow]
