["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
kind_of_gaction = "dbw2"
numtherm = 0
numsteps = 2
initial = "cold"
update_method = "HMC"

["Bias Settings"]
# general bias parameters
kind_of_bias = "parametric"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = true
symmetric = true
stride = 1
cvlims = [-5, 5]
biasfactor = "Inf"
# metadynamics specific parameters
bin_width = 0.02
meta_weight = 0.01
penalty_weight = 100
#
bias_Q = 0.0
bias_A = 200
bias_Z = 1.18

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]               
logdir = "./logs/L16x16x16x16_dbw2_beta1.25/test_topupdateC"
logfile = "logs.txt"
measurement_basedir = "./measurements/L16x16x16x16_dbw2_beta1.25/test_topupdateC"
measurement_dir = "raw_data"
randomseed = 0
verboselevel = 3
bias_basedir = "./metapotentials/L16x16x16x16_dbw2_beta1.25/test_topupdateC"
bias_dir = "bias"
overwrite = true
loadU_fromfile = true
loadU_format = "bridge"
loadU_dir = "./configs"
loadU_filename = "config_00000001.txt"

["Measurement Settings".measurements.Energy_density]
measure_every = 1
kinds_of_energy_density = ["plaquette", "clover"]

["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["plaquette", "clover"]

["Measurement Settings".measurements.Wilson_loop]
measure_every = 1
Rmax = 2
Tmax = 2

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 30
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 30

    ["Gradient Flow Settings".measurements_with_flow.Energy_density]
    measure_every = 1
    kinds_of_topological_charge = ["plaquette", "clover"]

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 1
    kinds_of_topological_charge = ["plaquette", "clover"]

    ["Gradient Flow Settings".measurements_with_flow.Wilson_loop]
    measure_every = 1
    Rmax = 2
    Tmax = 2

    ["Gradient Flow Settings".measurements_with_flow.Plaquette]
    measure_every = 1