["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
gauge_action = "dbw2"
numtherm = 50
numsteps = 1000
initial = "cold"
update_method = "HMC"

["Bias Settings"]
numinstances = 5
starting_Q = [-2, -1, 0, 1, 2]
kind_of_bias = "metad"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = false
symmetric = true
stride = 1
cvlims = [-3, 3]
biasfactor = inf
penalty_weight = 100
# metadynamics specific parameters
bin_width = 0.01
meta_weight = 0.000001
# opes specific parameters
barrier = 40
sigma0 = 0.1

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]               
ensemble_dir = "/ultz/gialu/repos/MetaQCD-dirac/ensembles/pure_dbw2_beta1.25_16_16_4smear_quad"
randomseed = 0
verboselevel = 1
overwrite = true

["Measurement Settings".measurements.Plaquette]
measure_every = 10

["Measurement Settings".measurements.Topological_charge]
measure_every = 10
type = ["clover"]
    
["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 30
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 10

    ["Gradient Flow Settings".measurements_with_flow.Plaquette]
    measure_every = 10

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    type = ["clover"]
