["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
kind_of_gaction = "dbw2"
numtherm = 20
numsteps = 1
initial = "cold"
update_method = "heatbath"
numheatbath = 1
numorelax = 4
eo = true
or_algorithm = "subgroups"

["Bias Settings"]
# general bias parameters
kind_of_bias = "metad"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = true
symmetric = true
stride = 1
cvlims = [-5, 5]
biasfactor = "Inf"
kinds_of_weights = ["tiwari", "branduardi", "balanced_exp"]
# metadynamics specific parameters
bin_width = 0.02
meta_weight = 0.01
penalty_weight = 1000
# opes specific parameters
barrier = 40
sigma0 = 0.1
# tempering specific parameters
tempering_enabled = true
numinstances = 2
swap_every = 1
non_metadynamics_updates = 1
measure_on_all = true

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"

["System Settings"]               
log_dir = "logs/L16x16x16x16_dbw2_beta1.25/test_ptmetad"
measurement_basedir = "measurements/L16x16x16x16_dbw2_beta1.25/test_ptmetad"
measurement_dir = "raw_data"
randomseed = 0
verboselevel = 2
bias_basedir = "metapotentials/L16x16x16x16_dbw2_beta1.25/test_ptmetad"
bias_dir = "bias"
overwrite = true

["Measurement Settings".measurements.Energy_density]
measure_every = 1
kinds_of_energy_density = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Gauge_action]
measure_every = 1
kinds_of_gauge_action = ["wilson", "symanzik_tree", "iwasaki", "dbw2"]

["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Polyakov_loop]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Wilson_loop]
measure_every = 1
Rmax = 2
Tmax = 2

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]

    ["Gradient Flow Settings".measurements_with_flow.Wilson_loop]
    measure_every = 10
    Rmax = 2
    Tmax = 2