["Physical Settings"]
L = [16, 16, 16, 16]
beta = 1.25
kind_of_gaction = "dbw2"
numtherm = 20
numsteps = 1000
initial = "cold"
update_method = "heatbath"
hb_maxit = 10
numheatbath = 1
eo = true
numorelax = 4
parity_update = true

["System Settings"]               
logdir = "./logs/L16x16x16x16_dbw2_beta1.25/test_heatbath"
logfile = "logs.txt"
measurement_basedir = "./measurements/L16x16x16x16_dbw2_beta1.25/test_heatbath"
measurement_dir = "raw_data"
randomseed = 0 # 0 => randomly chosen seed
verboselevel = 1
overwrite = true

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 10
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["clover"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 4
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 4

    [gradientflow_measurements.measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]
    methodname = "topological_charge"

