["Physical Settings"]
L = [12, 12, 12, 10]
beta = 6.0
kind_of_gaction = "wilson"
numtherm = 20
numsteps = 10
initial = "cold"
update_method = "heatbath"
hb_maxit = 10
numheatbath = 1
eo = true
or_algorithm = "subgroups"
numorelax = 4

["System Settings"]               
logdir = "./logs/L12x12x12x12_wilson_beta6.0/test_heatbath"
logfile = "logs.txt"
measurement_basedir = "./measurements/L12x12x12x12_wilson_beta6.0/test_heatbath"
measurement_dir = "raw_data"
randomseed = 2805
verboselevel = 1
overwrite = true

["Measurement Settings".measurements.Energy_density]
measure_every = 1
kinds_of_energy_density = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Gauge_action]
measure_every = 1
kinds_of_gauge_action = ["wilson", "symanzik_tree", "iwasaki", "dbw2"]

["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Polyakov_loop]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["plaquette", "clover", "improved"]

["Measurement Settings".measurements.Wilson_loop]
measure_every = 1
Rmax = 2
Tmax = 2

["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]

    ["Gradient Flow Settings".measurements_with_flow.Wilson_loop]
    measure_every = 10
    Rmax = 2
    Tmax = 2

