["Physical Settings"]
L = [12, 12, 12, 12]
beta = 3.938
gauge_action = "symanzik_tree"
numtherm = 50
numsteps = 100000
initial = "cold"
update_method = "hmc"

["Dynamical Fermion Settings"]
fermion_action = "staggered"
eo_precon = false
Nf = [2, 1]
mass = [0.00117229129, 0.033]
cg_tol_action = 1e-14
cg_tol_md = 1e-10
cg_maxiters_action = 5000
cg_maxiters_md = 5000
rhmc_spectral_bound = [0.00001, 6.0]
rhmc_prec_action = 64
rhmc_prec_md = 64

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"
hmc_numsmear_fermion = 2
hmc_rhostout_fermion = 0.15

["System Settings"]
ensemble_dir = "/ultz/gialu/repos/MetaQCD-dirac/ensembles/stagg_2stout0.15_ms0.033_lw_beta3.938_ns12_nt12"
randomseed = 0
verboselevel = 1
overwrite = true
to_console = false

["Measurement Settings".measurements.Plaquette]
measure_every = 10

["Measurement Settings".measurements.Topological_charge]
measure_every = 10
type = ["plaquette", "clover"]

["Measurement Settings".measurements.Energy_density]
measure_every = 10
type = ["clover"]
    
["Gradient Flow Settings"]
flow_integrator = "Cooling"
flow_num = 100
flow_measure_every = 100

    ["Gradient Flow Settings".measurements_with_flow.Plaquette]
    measure_every = 10

    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 10
    type = ["plaquette", "clover"]

    ["Gradient Flow Settings".measurements_with_flow.Energy_density]
    measure_every = 10
    type = ["clover"]
