["Physical Settings"]
L = [12, 12, 12, 12]
beta = 6.3188
kind_of_gaction = "wilson"
numtherm = 20
numsteps = 100
initial = "cold"
update_method = "hmc"
parity_update = false

["HMC Settings"]
hmc_deltatau = 0.02
hmc_steps = 50
hmc_integrator = "OMF4"

["System Settings"]               
logdir = "./logs/hmc_stability/wilson_dtau0.02"
logfile = "logs.txt"
measurement_basedir = "./measurements/hmc_stability/wilson_dtau0.02"
measurement_dir = "raw_data"
randomseed = 1206 # 0 => randomly chosen seed
verboselevel = 2
overwrite = true

# ["Measurement set".measurement_methods.Polyakov_loop]
# measure_every = 100
# methodname = "polyakov_loop"

# ["Measurement set".measurement_methods.Topological_charge]
# measure_every = 100
# kinds_of_topological_charge = ["clover"]
# methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 9
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 9

    [gradientflow_measurements.measurements_with_flow]


