["Physical Settings"]
L = [12, 12, 12, 12]
"β" = 6.0
kind_of_gaction = "wilson"
Ntherm = 10
Nsteps = 10
initial = "cold"
update_method = "heatbath"
hb_MAXIT = 10
hb_numHB = 1
eo = true
numOR = 4

["System Settings"]               
logdir = "./logs/PP/test_kl"
logfile = "test_kl.txt"
measurement_basedir = "./measurements/PP/test_kl"
measurement_dir = "test_kl"
randomseed = 1206
verboselevel = 1

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 10
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 10
kinds_of_topological_charge = ["clover"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "rk3"
flow_num = 7
flow_steps = 1
"flow_ϵ" = 0.12 # tflow is flow_num * flow_steps * flow_ϵ
flow_measure_every = 7

    [gradientflow_measurements.measurements_with_flow.Topological_charge]
    measure_every = 10
    methodname = "topological_charge"
    kinds_of_topological_charge = ["clover"]

    [gradientflow_measurements.measurements_with_flow.Plaquette]
    measure_every = 10
    methodname = "plaquette"


