[data]
float_type = "single"
solver_float_type = "single"
backend = "rocm"
ensemble_dir = "/home/gialu/projects/MetaQCD-CHMC/ensembles/constraint_test_14_2"
randomseed = 123
overwrite = true
verboselevel = 2
log_to_console = true
# save_config_every = 5
# save_config_format = "bridge"
load_config_format = "bridge"
load_config_fromfile = true
load_config_path = "/home/gialu/projects/MetaQCD-CHMC/ensembles/constraint_test_14/configs/config_00000005.txt"

[ensemble]
numinstances = 1
L = [14, 14, 14, 14]
numtherm = 0
numsteps = 5
numprocs_cart = [1, 1, 1, 1]
halo_width = 1
initial = "cold"
update_method = "hmc"
su3_nfloats = 18
mode = "sim"

[gauge_action]
beta = 6.1912
gauge_action = "wilson"

[bias]
recycle = true
rhostout_for_cv = 0.12 # rho is the same for all CVs
starting_Q = [0, 1]
[[bias.biases]]
type = "metad"
kind_of_cv = "topcharge_clover"
numsmears_for_cv = 1
static = true
symmetric = true
stride = 1
cvlims = [-3.0, 3.0]
biasfactor = 5
penalty_weight = 100.0
# opes specific parameters
barrier = 10.0
sigma_0 = 0.0
explore = false
# metad specific parameters
bin_width = 0.02
meta_weight = 0.05
load_bias = ["/home/gialu/ensembles/PP/topsusc_wilson_beta6.1912_14_14_build_7smear/biaspotentials/bias_000.metad"]

[hmc]
hmc_trajectory = 4
[[hmc.levels]]
forces = [0, 1]
integrator = "OMF4Constrained"
numsteps = 20

[gradient_flow]
flow_integrator = "euler"
flow_num = 30
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = [10, 20, 30]

[measurements.Plaquette]
measure_every = 100

[measurements.Topological_charge]
measure_every = 100
type = ["clover"]

[measurements_with_flow.Plaquette]
measure_every = 100

[measurements_with_flow.Topological_charge]
measure_every = 100
type = ["clover"]
