["Physical Settings"]
L = [12, 12, 12, 12]
beta = 6.0
kind_of_gaction = "wilson"
numtherm = 20
numsteps = 100
initial = "cold"
update_method = "HMC"

["Bias Settings"]
# general bias parameters
kind_of_bias = "metad"
kind_of_cv = "clover"
numsmears_for_cv = 4
rhostout_for_cv = 0.12
is_static = true
symmetric = true
stride = 1
cvlims = [-5, 5]
biasfactor = "Inf"
# metadynamics specific parameters
bin_width = 0.02
meta_weight = 0.01
penalty_weight = 1000
# usebiases = [
#     "./metapotentials/L16x16x16x16_dbw2_beta1.25/dummy.txt",
# ]

["HMC Settings"]
hmc_deltatau = 0.2
hmc_steps = 5
hmc_integrator = "OMF4"
# hmc_friction = 0.1

["System Settings"]               
logdir = "./logs/L12x12x12x12_wilson_beta6.0/test_metad"
logfile = "logs.txt"
measurement_basedir = "./measurements/L12x12x12x12_wilson_beta6.0/test_metad"
measurement_dir = "raw_data"
randomseed = 123
verboselevel = 1
bias_basedir = "./metapotentials/L12x12x12x12_wilson_beta6.0/test_metad"
bias_dir = "bias"
overwrite = true

["Measurement set".measurement_methods.Plaquette]
measure_every = 10
methodname = "plaquette"

[gradientflow_measurements]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12
flow_measure_every = 7

    [gradientflow_measurements.measurements_with_flow.Topological_charge]
    measure_every = 10
    kinds_of_topological_charge = ["clover"]
    methodname = "topological_charge"