["Physical Settings"]
L = [4, 4, 4, 4]
beta = 4.3
gauge_action = "symanzik_tree"
numtherm = 10
numsteps = 10
initial = "cold"
update_method = "hmc"
parity_update = false

["Dynamical Fermion Settings"]
fermion_action = "staggered"
eo_precon = false
Nf = [2]
mass = [0.01]
wilson_csw = 1.0
cg_tol_action = 1e-16
cg_tol_md = 1e-16
cg_maxiters_action = 5000
cg_maxiters_md = 5000
rhmc_spectral_bound = [0.0001, 6.0]
rhmc_prec_action = 64
rhmc_prec_md = 64

["HMC Settings"]
hmc_trajectory = 1
hmc_steps = 5
hmc_integrator = "OMF4"
hmc_numsmear_fermion = 4
hmc_rhostout_fermion = 0.12

["System Settings"]
float_type = "double"
ensemble_dir = "/home/gialuf/data/MetaQCD/test_fermions"
randomseed = 0
overwrite = true
save_checkpoint_every = 100
verboselevel = 1
log_to_console = true
# load_checkpoint_fromfile = true
# load_checkpoint_path = ""

["Measurement Settings".measurements]
["Measurement Settings".measurements.Plaquette]
measure_every = 1

["Measurement Settings".measurements.Topological_charge]
measure_every = 1
kinds_of_topological_charge = ["plaquette", "clover"]
# ["Measurement Settings".measurements.Eigenvalues]
# measure_every = 10
# dirac_type = "staggered"
# mass = 0.01
# nev = 1
# which = "LSM"
# ddaggerd = true
# maxdim = 20
    
["Gradient Flow Settings"]
flow_integrator = "euler"
flow_num = 7
flow_steps = 1
flow_tf = 0.12 # total flow time is flow_num * flow_tf
flow_measure_every = 7

    ["Gradient Flow Settings".measurements_with_flow]
    ["Gradient Flow Settings".measurements_with_flow.Plaquette]
    measure_every = 1
    #
    # ["Gradient Flow Settings".measurements_with_flow.Pion_correlator]
    # measure_every = 10
    # dirac_type = "wilson"
    # mass = 0.01
    # csw = 1.0
    # cg_tol = 1e-16
    # cg_maxiters = 5000
    #
    ["Gradient Flow Settings".measurements_with_flow.Topological_charge]
    measure_every = 1
    kinds_of_topological_charge = ["plaquette", "clover"]
    # ["Gradient Flow Settings".measurements_with_flow.Eigenvalues]
    # measure_every = 10
    # dirac_type = "staggered"
    # mass = 0.01
    # nev = 20
    # which = "SI"
    # ddaggerd = false
    # mindim = 20
    # maxdim = 40
