["Physical Settings"]
L = [4,4,4,4]
beta = 5.0

["Metadynamics Settings"]
meta_enabled = true
Qlims = [-7,7]
dq = 1e-3
#Qthrs = [-6,6]
w = 1e-4
k = 1000

["Simulation Settings"]
Ntherm = 1000
Nsweeps = 10000
initial = "hot"
tempering_enabled = false

["Monte-Carlo Settings"]
update_method = "HMC"
eps_hmc = 0.0002
hmc_steps = 100

["System Settings"]               
logdir = "./logs"
logfile = "meta/L4x4x4x4_beta5.0/Qlims(-7,7)_Qthr(-6.999,6.999)/dq1e-3_w1e-4_build.txt"
measurement_dir = "./measurements/meta/L4x4x4x4_beta5.0/Qlims(-7,7)_Qthr(-6.999,6.999)/dq1e-3_w1e-4_build"
savebias_dir = "./metapotentials"
biasfile = "L4x4x4x4_beta5.0/Qlims(-7,7)_Qthr(-6.999,6.999)/dq1e-3_w1e-4_build"